apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: argo-workflows-hub
  annotations:
    description: Kustomization for argo-workflow
labels:
  - pairs:
      app.kubernetes.io/instance: argo-workflows-hub

namespace: argo-workflows-hub
resources:
  - argo-workflows-css.yaml
  - argo-workflows-es.yaml

patches: []

helmGlobals:
  chartHome: charts
helmCharts:
  - releaseName: argo-workflows
    name: argo-workflows
    repo: https://argoproj.github.io/argo-helm/
    version: 0.46.1
    valuesFile: helm-argo-workflows-server.yaml
    additionalValuesFiles:
      - helm-argo-workflows-controller.yaml
      - helm-argo-workflows-workflow.yaml
    valuesInline:
      images:
        tag: v3.7.6
