apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflows
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-workflows-sa-secret
  annotations:
    kubernetes.io/service-account.name: argo-workflows
type: kubernetes.io/service-account-token
---
# ClusterRole for all argoproj.io resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-workflows-argoproj-admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups: ["argoproj.io"]
  resources: ["*"]
  verbs: ["*"]
---
# Bind argo-workflows SA with edit ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflows-k8s-edit-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: argo-workflows
---
# Bind argo-workflows SA with argoproj.io ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflows-argoproj-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-workflows-argoproj-admin
subjects:
- kind: ServiceAccount
  name: argo-workflows
