apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: argo-workflows-aws-security-account-ssm-th
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-southeast-7
